# Site settings
name: 翁
location: 佛山
company: alili
position: 前端打杂
github: https://github.com/
facebook: https://www.facebook.com/
phone: 1580424XXXX
email: xxxx@xxx.com

baseurl: "/"

permalink: /:year/:month/:day/:title/

exclude: ['README.md']

# Build settings
markdown: kramdown

